In [5]:
import numpy as np

In [6]:
python_list = [1, 2, 3, 4, 5]

#numpy list

np_array = np.array([1, 2, 3, 4, 5])

print("Python List:", python_list)
print("Numpy Arrat: ", np_array)
print("\nType of Python List:", type(python_list))
print("Type of Numpy Array: ", type(np_array))

#Key adventage: Vectorized operations (no loops needed)
#Adding 10 to each element

print("Python list (requires loop):", [x + 10 for x in python_list])
print("Nympy array (vectorized):", np_array + 10)

Python List: [1, 2, 3, 4, 5]
Numpy Arrat:  [1 2 3 4 5]

Type of Python List: <class 'list'>
Type of Numpy Array:  <class 'numpy.ndarray'>
Python list (requires loop): [11, 12, 13, 14, 15]
Nympy array (vectorized): [11 12 13 14 15]


# Creating Numpy Arrays

In [7]:
#Method 1 From Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("From list:", arr1 )

#Method 2 Using np.arrange() - similar to range()
arr2 = np.arange(0, 10, 2) #start, stop, step
print("Using arange:", arr2)

#Method 3 Using np.linspace() - evenly spaced numbers
arr3 = np.linspace(0, 1, 5) #start, stop, number of elements
print("Using linspace:", arr3)

#Method 4 Creating arrays of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

#Method 5 Creating arrays of ones
ones = np.ones(5)
print("Ones:", ones)

#Method 6 Creating arrays with a specific value
full = np.full(5, 7) #shape, fill value
print("Full all 7s:", full)

#Method 7 Identity matrix
identity = np.eye(3)
print("Identity matrix: \n", identity)

#Method 8 Random array
random_arr = np.random.rand(5) #uniform distribution [0, 1)
print("Random (uniform):", random_arr)

random_int = np.random.randint(1, 10, size=5) #[low, high), size    
print("Randon integers:", random_int)



From list: [1 2 3 4 5]
Using arange: [0 2 4 6 8]
Using linspace: [0.   0.25 0.5  0.75 1.  ]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Full all 7s: [7 7 7 7 7]
Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random (uniform): [0.05463819 0.46836991 0.35609271 0.5336174  0.31447726]
Randon integers: [9 1 5 3 7]


# Numpy Data Types (dtype)

In [8]:
#Type inference and common types
arr_int = np.array([1, 2, 3])
arr_float = np.array([0.5, 1.2, 1.5])
arr_mix = np.array([1, 1.5, 5, 2.2]) #mixed types -> pronted to float

print(f"Integer: {arr_int.dtype}")
print(f"Float: {arr_int.dtype}")
print(f"Mixed: {arr_int.dtype} (promoted float)\n")

#Specific types
arr1 = np.array([1, 2, 3], dtype=np.float32)
arr2 = arr_int.astype(np.float64) #convert types    

print(f"Specified float32: {arr1.dtype}")
print(f"Specified float64: {arr2.dtype}\n")

#Common types: int32, int64, float32, float64, bool
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element")



Integer: int64
Float: int64
Mixed: int64 (promoted float)

Specified float32: float32
Specified float64: float64

Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element


# Multi Dimemtional Arrays

In [9]:
#2D array (Matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix 2D: ")
print(matrix_2d)

print(f"Shape:{matrix_2d.shape}")
print(f"Dimentions: {matrix_2d.ndim}")
print(f"Size: {matrix_2d.size}")
print(f"Data Type: {matrix_2d.dtype}")

#3D array
matrix_3d = np.array([[1,2], [3, 4], [5,6], [7,8]])
print("3D array:")
print(matrix_3d)
print(f"Shape:{matrix_3d.shape}")

#Creating multi-dimensional arrays with specific shapes 

zeros_2d = np.zeros((3, 4)) #3row 4Columns
print("2D Zeros Array: ") 
print(zeros_2d)

ones_3d = np.ones((2, 3, 4)) #2x3x4
print("Ones 3D array: ")
print(ones_3d)

Matrix 2D: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:(3, 3)
Dimentions: 2
Size: 9
Data Type: int64
3D array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape:(4, 2)
2D Zeros Array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones 3D array: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# Indexing  and slicing
**Accesing and modifying array elements is similar to python but more powerful**


In [10]:
arr = np.array([10, 20, 30, 40, 50])

#1D indexing (same as python lists)
print("Original array: ", arr)
print("firts element: ", arr[0])
print("last element: ", arr[-1])
print("Element 1 to 3: ", arr[1:4])
print("Every other element: ", arr[::2])

#2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D array : \n", matrix)
print("Element at row 1 column 2: ", matrix[1, 2])
print("First Row: ", matrix[0, :])
print("First column: ", matrix[:, 0])
print("Submatrix (first 2 rows, first 2 columns):\n", matrix[0:2, 0:2])

#Boolean indexing - powerful feature 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("\n----boolean indexing-----")
print("Original array", arr)
print("Elements greater than 5: ", arr[arr > 5])
print("Even numbers: ", arr[arr % 2 == 0])



Original array:  [10 20 30 40 50]
firts element:  10
last element:  50
Element 1 to 3:  [20 30 40]
Every other element:  [10 30 50]

2D array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 column 2:  6
First Row:  [1 2 3]
First column:  [1 4 7]
Submatrix (first 2 rows, first 2 columns):
 [[1 2]
 [4 5]]

----boolean indexing-----
Original array [ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5:  [ 6  7  8  9 10]
Even numbers:  [ 2  4  6  8 10]


# Operations


In [11]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print("Array a:", a)
print("Array b:", b)

#Element-wise operations
print("\n---Element-wise Operations----")
print("Adition: ", a + b)
print("Substraction: ", a - b)
print("Multiplication: ", a * b) #Element-wise no matrix multiplication
print("Division: ", a / b)
print("Power (a**2):", a ** 2 )
print("Square root: ", np.sqrt(a))

#Scalar operations (broadcasting)
print("\n----Scalar operations-----")
print("a + 10: ", a + 10)
print("a * 2: ", a * 2)
print("a ** 3:", a ** 3)

#Comparition operations:
print("\n-----Comparition operations----")
print("a > 2: ", a > 2)
print("a == 3: ", a == 3)
print("a < = 2: ", a <= 2)


Array a: [1 2 3 4]
Array b: [5 6 7 8]

---Element-wise Operations----
Adition:  [ 6  8 10 12]
Substraction:  [-4 -4 -4 -4]
Multiplication:  [ 5 12 21 32]
Division:  [0.2        0.33333333 0.42857143 0.5       ]
Power (a**2): [ 1  4  9 16]
Square root:  [1.         1.41421356 1.73205081 2.        ]

----Scalar operations-----
a + 10:  [11 12 13 14]
a * 2:  [2 4 6 8]
a ** 3: [ 1  8 27 64]

-----Comparition operations----
a > 2:  [False False  True  True]
a == 3:  [False False  True False]
a < = 2:  [ True  True False False]


# Array manipulation: Reshaping and Resizing
**Chasing the shape of arrays is common in data processing**

In [12]:
arr = np.arange(12)
print("Original array: ", arr)

#Reshape - changes view, doesn't copy data
reshaped = arr.reshape(3, 4) #Must match total size (3*4=12)
print("Reshaped 3x4:\n ", reshaped)

#Flatten - convert to 1D
flattened = reshaped.flatten()
print("Flattened: \n", flattened)

#Reshape with -1 (auto-calculate dimension)
auto_reshape = arr.reshape(2, -1) #-1 means "calculate automatically"
print("\nAutoreshape (2 rows, auto-columns): ")
print(auto_reshape)

#Transpose
matrix = np.array([[1,2,3], [4,5,6]])
print("\nOriginal Matrix: ")
print(matrix)
print("Transposed: ")
print(matrix.T)

#Concatenation
a = np.array([[1,2], [3, 4]])
b = np.array([[5, 6], [7,8]])

print("----Concatenation----")
print("Array a: \n", a)
print("Array b: \n", b)
print("Vertical concatenation (vstack):")
print(np.vstack((a, b)))
print("Horizontal concatenation (hstack):")
print(np.hstack((a, b)))
print("Using Concatenate:")
print(np.concatenate((a, b), axis=0)) #axis 0 for vertical
print(np.concatenate((a, b), axis=1)) #axis 1 for horizontal

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Autoreshape (2 rows, auto-columns): 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Original Matrix: 
[[1 2 3]
 [4 5 6]]
Transposed: 
[[1 4]
 [2 5]
 [3 6]]
----Concatenation----
Array a: 
 [[1 2]
 [3 4]]
Array b: 
 [[5 6]
 [7 8]]
Vertical concatenation (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal concatenation (hstack):
[[1 2 5 6]
 [3 4 7 8]]
Using Concatenate:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Understanding Dimensions and Axis
**KEY CONCEPTS**
* **Dimension (ndim)**: Number of axes (1D, 2D, 3D)
* **Axis**: The dimension along which an operation is performed (starts at 0)
* **Shape**: Size of each dimension (e.g, (3, 4) = 3 rows and 4 columns)
* **For 2D arrays**: axis=0 = rows (vertical), axis=1 = columns (horizontal)   

In [13]:
#Understanding dimensions
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("1D array: ")
print(f"{arr_1d} -> shape: {arr_1d.shape} ndim -> {arr_1d.ndim}, (axis 0 only)\n") 

print("2D array:")
print(f"{arr_2d}")
print(f"shape: {arr_2d.shape} (rows, columns)")
print(f"Ndim --> {arr_2d.ndim}, (axis 0=rows, axis 1=columns)")

1D array: 
[1 2 3 4 5] -> shape: (5,) ndim -> 1, (axis 0 only)

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3) (rows, columns)
Ndim --> 2, (axis 0=rows, axis 1=columns)


In [14]:
#Axis in operations: specifies which dimension to collapse 
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Matrix")
print(matrix)
print(f"shape -> {matrix.shape}\n")

#axis=0: collapse rows (operate down columns) -> one value per column
sum_axis0 = np.sum(matrix, axis=0)
print(f"axis=0 (down rows): {sum_axis0} -> shape: {sum_axis0.shape}")
print(f"Example -> column 0 sum = {matrix[0, 0]} + {matrix[1, 0]} + {matrix[2, 0]} = {sum_axis0[0]}\n")

#axis=1: collapse columns (operate across rows) -> one value per row 
sum_axis1 = np.sum(matrix, axis=1)
print(f"axis=1 (across columns): {sum_axis1} -> shape {sum_axis1.shape}")
print(f"Example -> row 0 sum = {matrix[0, 0]} + {matrix[0,1] } + {matrix[0, 2]} = {sum_axis1[0]}\n ")



Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape -> (3, 3)

axis=0 (down rows): [12 15 18] -> shape: (3,)
Example -> column 0 sum = 1 + 4 + 7 = 12

axis=1 (across columns): [ 6 15 24] -> shape (3,)
Example -> row 0 sum = 1 + 2 + 3 = 6
 


In [15]:
# 3D array: Axis with more than 2 dimensions
# Think: (depth, rows, columns) or (samples, height, width)

arr_3d = np.array([
    [[1,2,3],
     [4,5,6]], #firts 2d slice (page 0) 
    [[7,8,9],
     [10,11,12]] #second 2d slice (page 1)
])

print("3D array (shape: 2x2x3):")
print(arr_3d)
print(f"shape -> {arr_3d.shape} (depth:2, rows:2, comlumns:3)\n")

#axis=0 collapse depth (across pages) result -> 2D (2x3)
sum_axis0 = np.sum(arr_3d, axis=0)
print(f"axis=0 (across pages):\n {sum_axis0} -> shape: {sum_axis0.shape}")
print(f"Example: [0,0,0] = {arr_3d[0,0,0]} + {arr_3d[1,0,0]} = {sum_axis0[0,0]}\n" )

#axis=1: collapse rows (down each page) -> result: 2D (2x3)
sumaxis0= np.sum(arr_3d, axis=1)
print(f"axis=1 (down rows): \n {sumaxis0} -> shape: {sumaxis0.shape}")
print(f"Example [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,1,0]} = {sumaxis0[0,0]}\n")

#axis=2: collapse colums (across each row) -> resulto: 2d (2x2)
sum_axis2 = np.sum(arr_3d, axis=2)
print(f"axis=2 (across columns): \n{sum_axis2} -> shape: {sum_axis2.shape}")
print(f"Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,0,1]} + {arr_3d[0,0,2] } = {sum_axis2[0,0]}\n ")




3D array (shape: 2x2x3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape -> (2, 2, 3) (depth:2, rows:2, comlumns:3)

axis=0 (across pages):
 [[ 8 10 12]
 [14 16 18]] -> shape: (2, 3)
Example: [0,0,0] = 1 + 7 = 8

axis=1 (down rows): 
 [[ 5  7  9]
 [17 19 21]] -> shape: (2, 3)
Example [0,0] = 1 + 4 = 5

axis=2 (across columns): 
[[ 6 15]
 [24 33]] -> shape: (2, 2)
Example: [0,0] = 1 + 2 + 3 = 6
 


In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

#basic statistics
print(f"\n ----------Basic Statistics------------")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standart desviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Index of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")

# 2D array statistics (with axis parameter)
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])
print("\n -----2D array Statistics ------")
print("Matrix: ")
print(matrix)
print(f"Sum of all elements: {np.sum(matrix)}")
print(f"sum along row (axis=0): {np.sum(matrix, axis=0)}") #column sums
print(f"Sum along colums (axis=1): {np.sum(matrix, axis=1)}") # Row sums
print(f"Mean of each column: {np.mean(matrix, axis = 0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}") 


[ 1  2  3  4  5  6  7  8  9 10]

 ----------Basic Statistics------------
Sum: 55
Mean: 5.5
Median: 5.5
Standart desviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Index of min: 0
Index of max: 9

 -----2D array Statistics ------
Matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
sum along row (axis=0): [12 15 18]
Sum along colums (axis=1): [ 6 15 24]
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


# Linear Algebra Operations
* Numpy includes powerful algebra functions

In [24]:
#Matrix multiplications
a = np.array([[1, 2], [3,4]])
b = np.array([[5,6], [7,8]])
print("Matrix a:")
print(a)
print("\nMatrix b:")
print(b)

#Element-wise multiplication (NOT matrix multiplication)
print("Element-wise operations a*b:")
print(a*b)

#Dot products of vectors 
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print(f"\nDot product of vectors {v1} and {v2}: {np.dot(v1, v2)}")

#Matrix properties
matrix = np.array([[1,2], [3,4]])
print("\n---Matrix properties---")
print("Matrix:")
print(matrix)
print(f"Determinant: {np.linalg.det(matrix)}")
print(f"Inverse: {np.linalg.inv(matrix)}")
print("Transpose: \n", matrix.T)   

#Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(matrix)
print(f"Eigenvaluess:\n {eigenvals}")
print(f"Eigenvectors:\n {eigenvecs}")

Matrix a:
[[1 2]
 [3 4]]

Matrix b:
[[5 6]
 [7 8]]
Element-wise operations a*b:
[[ 5 12]
 [21 32]]

Dot product of vectors [1 2 3] and [4 5 6]: 32

---Matrix properties---
Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Transpose: 
 [[1 3]
 [2 4]]
Eigenvaluess:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Array methods


In [ ]:
arr = np.array([3,1,4,1,5,9,2,6,5,4,1,1,6,6])
print("Original array:\n", arr)

# sorting
print("----------Sorting ------------")
print("Sorted array: ", np.sort(arr))
print("Original Unchanged:", arr)
arr.sort()
print("Array after in-place sort: ", arr)

#Unique elements
print("Unique values: ",np.unique(arr))

#Searching
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("--------Searching----------")
print("Array: ", arr)
print("Where is value > 5: ", np.where(arr > 5))
print("Where condition is true: ", arr[np.where(arr>5)])

#stacking array


Original array:
 [3 1 4 1 5 9 2 6 5 4 1 1 6 6]
----------Sorting ------------
Sorted array:  [1 1 1 1 2 3 4 4 5 5 6 6 6 9]
Original Unchanged: [3 1 4 1 5 9 2 6 5 4 1 1 6 6]
Array after in-place sort:  [1 1 1 1 2 3 4 4 5 5 6 6 6 9]
Unique values:  [1 2 3 4 5 6 9]
--------Searching----------
Array:  [ 1  2  3  4  5  6  7  8  9 10]
Where is value > 5:  (array([5, 6, 7, 8, 9]),)
Where condition is true:  [ 6  7  8  9 10]
